baseURL = 'https://weasel-shiro.github.io'
languageCode = 'en-us'
title = 'Weasel Shiro'
theme = 'PaperMod'


[params]
  homeInfoParams = { Title = "Hola, soy Weasel Shiro ðŸ¦¦", Content = "Streamer de videojuegos y entusiasta de Guild Wars 2. Bienvenido a mi pÃ¡gina!" }
  ShowReadingTime = false
  ShowBreadCrumbs = false
  ShowPostNavLinks = false
  ShowShareButtons = false